from sqlalchemy import Column, Integer, String, Float, Text, ForeignKey
from sqlalchemy.orm import relationship
from core.database import Base


class Season(Base):
    __tablename__ = "seasons"

    year = Column(Integer, primary_key=True)
    startDate = Column(Text)
    endDate = Column(Text)
    displayName = Column(Text)


class Team(Base):
    __tablename__ = "teams"

    id = Column(Text, primary_key=True)
    uid = Column(Text)
    slug = Column(Text)
    abbreviation = Column(Text)
    displayName = Column(Text)
    name = Column(Text)
    nickname = Column(Text)
    location = Column(Text)
    color = Column(Text)
    alternateColor = Column(Text)
    logos = Column(Text)


class Player(Base):
    __tablename__ = "players"

    id = Column(Text, primary_key=True)
    uid = Column(Text)
    guid = Column(Text)
    firstName = Column(Text)
    lastName = Column(Text)
    displayName = Column(Text)
    shortName = Column(Text)
    weight = Column(Float)
    displayWeight = Column(Text)
    height = Column(Float)
    displayHeight = Column(Text)
    birthPlace_city = Column(Text)
    birthPlace_state = Column(Text)
    birthPlace_country = Column(Text)
    experience_years = Column(Integer)
    experience_displayValue = Column(Text)
    experience_abbreviation = Column(Text)
    jersey = Column(Text)
    hand_type = Column(Text)
    hand_abbreviation = Column(Text)
    hand_displayValue = Column(Text)


class PlayerSeason(Base):
    __tablename__ = "player_seasons"

    season_player_id = Column(Text, primary_key=True)
    season = Column(Text, ForeignKey("seasons.year"))
    player_id = Column(Text, ForeignKey("players.id"))
    uid = Column(Text)
    guid = Column(Text)
    firstName = Column(Text)
    lastName = Column(Text)
    fullName = Column(Text)
    displayName = Column(Text)
    shortName = Column(Text)
    weight = Column(Float)
    displayWeight = Column(Text)
    height = Column(Float)
    displayHeight = Column(Text)
    birthPlace_city = Column(Text)
    birthPlace_state = Column(Text)
    birthPlace_country = Column(Text)
    slug = Column(Text)
    headshot = Column(Text)
    jersey = Column(Text)
    hand_type = Column(Text)
    hand_abbreviation = Column(Text)
    hand_displayValue = Column(Text)
    flag_href = Column(Text)
    position_id = Column(Text)
    position_name = Column(Text)
    position_abbreviation = Column(Text)
    position_displayValue = Column(Text)
    team_id = Column(Text, ForeignKey("teams.id"))
    experience_years = Column(Integer)
    experience_displayValue = Column(Text)
    experience_abbreviation = Column(Text)


class Game(Base):
    __tablename__ = "games"

    id = Column(Text, primary_key=True)
    uid = Column(Text)
    season_year = Column(Integer, ForeignKey("seasons.year"))
    season_type = Column(Integer)
    week = Column(Integer)
    game_note = Column(Text)
    timeValid = Column(Integer)
    date = Column(Text)
    is_neutral_site = Column(Integer)
    is_conference_competition = Column(Integer)
    event_status_id = Column(Text)
    event_status_name = Column(Text)
    event_status_state = Column(Text)
    event_status_completed = Column(Integer)
    event_status_description = Column(Text)
    event_status_detail = Column(Text)
    event_status_short_detail = Column(Text)
    event_tournament_id = Column(Text)
    venue_id = Column(Text)
    attendance = Column(Integer)
    officials = Column(Text)
    home_team_id = Column(Text, ForeignKey("teams.id"))
    home_team_winner = Column(Integer)
    home_team_score = Column(Integer)
    home_linescores = Column(Text)
    home_team_records = Column(Text)
    home_team_guid = Column(Text)
    home_team_uid = Column(Text)
    home_team_location = Column(Text)
    home_team_name = Column(Text)
    home_team_abbreviation = Column(Text)
    home_team_nickname = Column(Text)
    home_team_displayName = Column(Text)
    home_team_color = Column(Text)
    home_team_alternate_color = Column(Text)
    home_team_logos = Column(Text)
    home_team_conference_id = Column(Text)
    home_team_conference_slug = Column(Text)
    away_team_id = Column(Text, ForeignKey("teams.id"))
    away_team_winner = Column(Integer)
    away_team_score = Column(Integer)
    away_linescores = Column(Text)
    away_team_records = Column(Text)
    away_team_guid = Column(Text)
    away_team_uid = Column(Text)
    away_team_location = Column(Text)
    away_team_name = Column(Text)
    away_team_abbreviation = Column(Text)
    away_team_nickname = Column(Text)
    away_team_displayName = Column(Text)
    away_team_color = Column(Text)
    away_team_alternate_color = Column(Text)
    away_team_logos = Column(Text)
    away_team_conference_id = Column(Text)
    away_team_conference_slug = Column(Text)


class TeamBoxscore(Base):
    __tablename__ = "team_boxscores"

    event_team_id = Column(Text, primary_key=True)
    event_id = Column(Text, ForeignKey("games.id"))
    team_id = Column(Text, ForeignKey("teams.id"))
    home_away = Column(Text)
    fieldGoalsMade = Column(Text)
    fieldGoalsAttempted = Column(Text)
    fieldGoalPct = Column(Text)
    threePointFieldGoalsMade = Column(Text)
    threePointFieldGoalsAttempted = Column(Text)
    threePointFieldGoalPct = Column(Text)
    freeThrowsMade = Column(Text)
    freeThrowsAttempted = Column(Text)
    freeThrowPct = Column(Text)
    totalRebounds = Column(Text)
    offensiveRebounds = Column(Text)
    defensiveRebounds = Column(Text)
    assists = Column(Text)
    steals = Column(Text)
    blocks = Column(Text)
    turnovers = Column(Text)
    teamTurnovers = Column(Text)
    totalTurnovers = Column(Text)
    technicalFouls = Column(Text)
    flagrantFouls = Column(Text)
    fouls = Column(Text)
    largestLead = Column(Text)


class PlayerBoxscore(Base):
    __tablename__ = "player_boxscores"

    event_athlete_id = Column(Text, primary_key=True)
    event_id = Column(Text, ForeignKey("games.id"))
    athlete_id = Column(Text, ForeignKey("players.id"))
    team_id = Column(Text, ForeignKey("teams.id"))
    athlete_name = Column(Text)
    athlete_headshot = Column(Text)
    athlete_jersey = Column(Text)
    athlete_position_name = Column(Text)
    athlete_position_abbreviation = Column(Text)
    athlete_position_display_name = Column(Text)
    athlete_starter = Column(Integer)
    athlete_did_not_play = Column(Integer)
    athlete_ejected = Column(Integer)
    MIN = Column(Text)
    FG = Column(Text)
    three_PT = Column("3PT", Text)
    FT = Column(Text)
    OREB = Column(Text)
    DREB = Column(Text)
    REB = Column(Text)
    AST = Column(Text)
    STL = Column(Text)
    BLK = Column(Text)
    TO = Column(Text)
    PF = Column(Text)
    PTS = Column(Text)


class Prediction(Base):
    __tablename__ = "predictions"

    event_id = Column(Text, ForeignKey("games.id"), primary_key=True)
    name = Column(Text)
    short_name = Column(Text)
    homeTeam_team_id = Column(Text, ForeignKey("teams.id"))
    homeTeam_gameProjection = Column(Float)
    homeTeam_gameProjection_display = Column(Text)
    homeTeam_teamChanceLoss = Column(Float)
    homeTeam_teamChanceLoss_display = Column(Text)
    awayTeam_team_id = Column(Text, ForeignKey("teams.id"))
    awayTeam_gameProjection = Column(Float)
    awayTeam_gameProjection_display = Column(Text)
    awayTeam_teamChanceLoss = Column(Float)
    awayTeam_teamChanceLoss_display = Column(Text)


class Odds(Base):
    __tablename__ = "odds"

    event_provider_id = Column(Text, primary_key=True)
    event_id = Column(Text, ForeignKey("games.id"))
    provider_id = Column(Text)
    provider_name = Column(Text)
    details = Column(Text)
    over_under = Column(Float)
    spread = Column(Float)
    over_odds = Column(Integer)
    under_odds = Column(Integer)
    away_team_favorite = Column(Integer)
    away_team_underdog = Column(Integer)
    away_team_moneyline = Column(Integer)
    away_team_spread_odds = Column(Integer)
    away_team_spread = Column(Text)
    away_team_id = Column(Text, ForeignKey("teams.id"))
    home_team_favorite = Column(Integer)
    home_team_underdog = Column(Integer)
    home_team_moneyline = Column(Integer)
    home_team_spread_odds = Column(Integer)
    home_team_spread = Column(Text)
    home_team_id = Column(Text, ForeignKey("teams.id"))


class Ranking(Base):
    __tablename__ = "rankings"

    season_week_team = Column(Text, primary_key=True)
    season = Column(Text, ForeignKey("seasons.year"))
    week = Column(Integer)
    team_id = Column(Text, ForeignKey("teams.id"))
    week_displayValue = Column(Text)
    headline = Column(Text)
    short_headline = Column(Text)
    season_displayName = Column(Text)
    ranking_provider_id = Column(Text)
    ranking_provider_name = Column(Text)
    ranking_provider_type = Column(Text)
    current_rank = Column(Integer)
    previous_rank = Column(Integer)
    first_place_votes = Column(Integer)
    points = Column(Float)
    trend = Column(Text)
    record_summary = Column(Text)
    record_wins = Column(Integer)
    record_losses = Column(Integer)
    record_ties = Column(Integer)
    ranked_type = Column(Text)
